### ISSUE TITLE
Universal links not working

### ISSUE THREAD

**Issue by tomislav** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#170] opened 2015-09-12 10:28 UTC
I can't get universal links to work in iOS 9. I followed the guide and everything is setup properly in the app, on the apple dev portal, in the provisioning profiles and in the branch dashboard. Minimum deployment target is iOS 8.2.

I've checked my device logs and it seems there is some error with the `apple-app-site-association` on the branch website. SSL certificate troubles?

```
Sep 12 12:19:01 TF6 swcd[270] <Notice>: 2015-09-12 12:19:01.811913 PM [SWC] ### Rejecting URL 'https://htl.st/apple-app-site-association' for auth method 'NSURLAuthenticationMethodServerTrust': -6754/0xFFFFE59E kAuthenticationErr
```

Bundle id is `com.hitlistapp.ios` 

My entitlements file:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>com.apple.developer.associated-domains</key>
        <array>
            <string>applinks:bnc.lt</string>
            <string>applinks:htl.st</string>
        </array>
        <key>com.apple.security.application-groups</key>
        <array>
            <string>group.com.hitlistapp.ios</string>
        </array>
    </dict>
</plist>
```

**Comment by shortstuffsushi** [comment] 2015-09-12 16:23
Hmm, it appears that there may be an issue with white listed domains and SSL validation. I checked `htl.st` using [my validation tool](http://limitless-sierra-4673.herokuapp.com/), and got the following output in the server logs.

```
Error: Hostname/IP doesn't match certificate's altnames: "Host: htl.st. is not in the cert's altnames: DNS:branch.io, DNS:api.branch.io, DNS:dashboard.branch.io, DNS:bnc.lt"
```

**Comment by shortstuffsushi** [comment] 2015-09-12 16:29
However, I also tried just running `bnc.lt` and checking for your app in there. It looks like there is a listing for `com.hitlistapp.ios`, so if (for the sake of testing), you were to only use `bnc.lt` in your domains, you should be able to see it work.

**Comment by tomislav** [comment] 2015-09-12 16:57
It works if I use bnc.lt, sort of. The deep link handler gets called only on app resume, not app launch.

`continueUserActivity` is called both times, but the payload is missing on cold app launch.

Log on app resume:
```
Sep 12 18:49:20 TF6 Hitlist[1978] <Warning>: continueUserActivity called
Sep 12 18:49:20 TF6 Hitlist[1978] <Warning>: encoded dictionary : {"ios_bundle_id":"com.hitlistapp.ios","app_version":"3.1","device_fingerprint_id":"120531804238121774","update":1,"os":"iOS","universal_link_url":"http://bnc.lt/7xEc/Gh5Czvnqzm","identity_id":"132924250574034782","debug":1,"sdk":"ios0.11.0","retryNumber":0,"branch_key":"xxxxx","is_referrable":0,"os_version":"9.0","ad_tracking_enabled":0,"ios_team_id":"XHXW98V3YD","uri_scheme":"hitlistapp"}
Sep 12 18:49:20 TF6 Hitlist[1978] <Warning>: [BNCServerInterface.m:153] using url = https://api.branch.io/v1/open
Sep 12 18:49:20 TF6 Hitlist[1978] <Warning>: [BNCServerInterface.m:154] body = {
	    "ad_tracking_enabled" = 0;
	    "app_version" = "3.1";
	    "branch_key" = "xxxxx";
	    debug = 1;
	    "device_fingerprint_id" = 120531804238121774;
	    "identity_id" = 132924250574034782;
	    "ios_bundle_id" = "com.hitlistapp.ios";
	    "ios_team_id" = XHXW98V3YD;
	    "is_referrable" = 0;
	    os = iOS;
	    "os_version" = "9.0";
	    retryNumber = 0;
	    sdk = "ios0.11.0";
	    "universal_link_url" = "http://bnc.lt/7xEc/Gh5Czvnqzm";
	    update = 1;
	    "uri_scheme" = hitlistapp;
	}
Sep 12 18:49:21 TF6 Hitlist[1978] <Warning>: [BNCServerInterface.m:196] returned = Status: 200; Data: {
	    "browser_fingerprint_id" = "<null>";
	    data = "{\"$og_description\":\"The best flight deals for an upcoming weekend, to cities near you.\",\"$og_image_url\":\"https://static.hitlistapp.com/media/CACHE/images/trips/3/weekend/0d0c1316af24a0bff1bd13b925ca082e.jpeg\",\"$og_title\":\"Weekend Getaways\",\"action\":\"trip\",\"id\":3,\"referring_user_id\":\"31459\",\"referring_user_name\":\"Tomislav Filipcic\",\"title\":\"Weekend Getaways\",\"~channel\":\"other\",\"~feature\":\"trips\",\"~creation_source\":\"iOS SDK\",\"+match_guaranteed\":true,\"+click_timestamp\":1442076561,\"+is_first_session\":false,\"+clicked_branch_link\":true}";
	    "device_fingerprint_id" = 120531804238121774;
	    identity = 31459;
	    "identity_id" = 132924250574034782;
	    link = "http://htl.st/j/Wd3Rt8pXYj";
	    "referring_identity" = 31459;
	    "session_id" = 171288389545366697;
	}
Sep 12 18:49:21 TF6 Hitlist[1978] <Warning>: Branch deep link params: {
	    "$og_description" = "The best flight deals for an upcoming weekend, to cities near you.";
	    "$og_image_url" = "https://static.hitlistapp.com/media/CACHE/images/trips/3/weekend/0d0c1316af24a0bff1bd13b925ca082e.jpeg";
	    "$og_title" = "Weekend Getaways";
	    "+click_timestamp" = 1442076561;
	    "+clicked_branch_link" = 1;
	    "+is_first_session" = 0;
	    "+match_guaranteed" = 1;
	    action = trip;
	    id = 3;
	    "referring_user_id" = 31459;
	    "referring_user_name" = "Tomislav Filipcic";
	    title = "Weekend Getaways";
	    "~channel" = other;
	    "~creation_source" = "iOS SDK";
	    "~feature" = trips;
	}
```

Log on cold app launch
```
Sep 12 18:50:40 TF6 Hitlist[1980] <Warning>: continueUserActivity called
Sep 12 18:50:40 TF6 Hitlist[1980] <Warning>: [BNCServerInterface.m:196] returned = Status: 200; Data: {
	    "browser_fingerprint_id" = "<null>";
	    data = "{\"+is_first_session\":false,\"+clicked_branch_link\":false}";
	    "device_fingerprint_id" = 120531804238121774;
	    identity = 31459;
	    "identity_id" = 132924250574034782;
	    link = "http://htl.st/j/Wd3Rt8pXYj";
	    "session_id" = 171288723319690553;
	}
Sep 12 18:50:40 TF6 Hitlist[1980] <Warning>: Branch deep link params: {
	    "+clicked_branch_link" = 0;
	    "+is_first_session" = 0;
	}
```

**Comment by shortstuffsushi** [comment] 2015-09-12 17:06
Could you tell me what the difference is between the webpageURL for both of those? It seems that's really all that's being [checked](https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/4c3b2a5a6d34e2971efb53bab5a5bf0caa55a393/Branch-SDK/Branch-SDK/Branch.m#L360), so I'm not sure why the behavior would differ between start and resume.

**Comment by tomislav** [comment] 2015-09-12 17:10
I'm using this link in both cases: http://htl.st/7xEc/Gh5Czvnqzm . I just changed the htl.st to bnc.lt so it's http://bnc.lt/7xEc/Gh5Czvnqzm

Not sure if that's what you're asking.

**Comment by shortstuffsushi** [comment] 2015-09-12 17:14
Sorry, I actually meant in the code, when it reached that check. If you inspect the webpageURL for both of those scenarios, I was thinking there may be a difference. If not, I'm wondering if there may be a race condition, depending on when `initSession` is called vs when `continueUserActivity` occurs.

**Comment by tomislav** [comment] 2015-09-12 17:21
On resume webpageURL is `http://bnc.lt/7xEc/Gh5Czvnqzm` 
On launch webpageURL is `http://bnc.lt/7xEc/Gh5Czvnqzm`

**Comment by aaustin** [comment] 2015-09-14 04:00
@tomislav thanks for the note - we're going to investigate first thing tomorrow.

**Comment by derrickstaten** [comment] 2015-09-14 19:03
@tomislav we've opened a PR here: https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/pull/174

We need to do more testing but if you need an urgent fix I suggest trying this out. Feel free to leave feedback

**Comment by derrickstaten** [comment] 2015-09-14 21:23
@tomislav this is now resolved in the newly released version, `0.11.1`. Thanks so much for letting us know. We're going to reach out to other partners using `0.11.0`.

**Comment by francisjervis** [comment] 2015-09-14 21:55
Links are not opening the app from cold for me. Works when the app is already open, otherwise goes to deepview; app open after clicking a link (and getting dv) “gets” the link...

**Comment by tomislav** [comment] 2015-09-14 21:58
Thanks. What about the issue with using custom domains (SSL error when fetching the apple-app-site-association file)? Is this something you will be able to solve?

**Comment by derrickstaten** [comment] 2015-09-14 22:06
@francisjervis can you send in a message to support@branchmetrics.io ticket with the link, the SDK version, and when you're clicking on the link? Please also provide the OS (iOS 8 or 9) and whether you've set up Universal Links. This is likely a separate issue, as it has to do with redirection rather than fetching params inside the app

**Comment by derrickstaten** [comment] 2015-09-14 22:08
@tomislav I want to be able to reproduce this. Can you shoot us a note with your Branch Key (support@branchmetrics.io with subject `ATTN: Derrick (SSL UL issue)`)? Then I can set up my app with analogous configuration and see if I can recreate.

**Comment by tomislav** [comment] 2015-09-14 22:18
@derrickstaten I just did.

Reading through the Apple's documentation it seems to me that the solution would be to serve proper valid SSL certificates for all alias domains. Since iOS won't do a redirect when fetching the `apple-app-site-association` file.

**Comment by derrickstaten** [comment] 2015-09-15 04:41
I am able to setup the Associated Domains to be an aliased domain and have Apple scrape https://bnc.lt/apple-app-site-association. @tomislav I sent a follow up email with how we've done it using CloudFlare. As long as you can get SSL set up appropriately there, it should work.

**Closed by derrickstaten** 2015-09-15 04:41 UTC

**Comment by marcshilling** [comment] 2016-01-05 20:15
Had this issue too (Universal Links weren't working on cold boot)

If you're ALSO integrating the Facebook SDK, they instruct you to make the last line of your `didFinishLaunching` method:
```
return [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
```
I discovered this actually prevents the `continueUserActivity` AppDelegate method from firing on a cold boot, which breaks universal links. Changing the end of my `didFinishLaunching` to:
```    
[[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
return YES;
``` 
fixed the issue. Hope this helps someone else!
