### ISSUE TITLE
Deep link handler not called on launch 

### ISSUE THREAD

**Issue by tomislav** [BranchMetrics/iOS-Deferred-Deep-Linking-SDK#142] opened 2015-07-04 13:10 UTC
Since updating to 0.10.0 I have an issue where the deep link handler is not called on app launch (works fine on resume). Also broken in 0.9.3. I had to downgrade to 0.8.4 to get it working again. 

Nothing in *error, it just doesn't get called. I'm not sure if I'm missing something on upgrading.

```
    Branch *branch = [Branch getInstance];
    [branch initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        if (!error) {
            DDLogDebug(@"Branch deep link params: %@", [params description]);
             [self processBranchPayloadWithParams:params];
        } else {
            DDLogDebug(@"Branch error: %@", error);
        }
    }];
```

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    DDLogDebug(@"Deep link url: %@", url);
    if ([url.scheme hasPrefix:@"fb"]) {
        return [FBSession.activeSession handleOpenURL:url];
    } else if ([[Branch getInstance] handleDeepLink:url]) {
        return YES;
    } else {
        [self processURLSchemeWithURL:url];
        return YES;
    }
}
```

**Comment by francisjervis** [comment] 2015-07-04 16:29
This may or may not fix this, but my (Swift, working) code for openURL returns false (= NO) for Branch URLs, else true:

    func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject?) -> Bool {
        
        NSLog("%@","got url \(url)")


        if (!Branch.getInstance().handleDeepLink(url)) {

            NSLog("%@","isnt branch")
        
            return true
        }
        
        else {
            NSLog("%@","is branch")
            
            NSLog("%@","params \(branchParams)")

            
            return false
        }
    }

**Comment by aaustin** [comment] 2015-07-04 16:40
Tomis - is the initSession code in the didFinishLaunching section? Or where else are you be calling it? My testbed seems to work fine.

**Comment by aaustin** [comment] 2015-07-04 16:50
Also, @tomislav, there is a code path where we don't call initSession if the following is true:
    if (![options objectForKey:UIApplicationLaunchOptionsURLKey]) {

Then, since you have us after Facebook in openUrl, it's possible Facebook is stealing the first launch URL key? Can you try moving our handleDeepLink call above Facebook's?

**Comment by tomislav** [comment] 2015-07-08 17:08
Yes, it's in didFinishLaunchingWithOptions. One thing I remember seeing was a lot of timeouts to the branch server (some api call with "open" and "v1"), but I'm not sure if it was related (would that still call the handler, but with an error?). I'll try it with Debug turned on to see what's going on.

**Comment by shortstuffsushi** [comment] 2015-07-13 14:25
Hi all, sorry for the delay -- I was out of town last week. I'm not sure where exactly this stands, but one of the things I wanted to point out was what Francis had said -- if there is a notification in the app, we expect to hit the `handleOpenUrl` in order to initialize the SDK, whether it's our notification or not. What may help is changing to this:

```
BOOL handledByBranch = [[Branch getInstance] handleDeepLink:url];
BOOL handledByFb = [FBSession.activeSession handleOpenURL:url];

if (!handleByBranch && !handleByFb) {
    [self processURLSchemeWithURL:url];
}

return YES;
```

This way both of the frameworks will *always* get their chance to try to handle the notification first.

Additionally, you mentioned things about timeouts and Branch server issues; were you able to find anything further on this? I'll try to reproduce locally today as well.

**Comment by SergeyMagid** [comment] 2015-07-16 09:06
Hi all
I have the same problem at Android. Time to time branch.initSession did not call callback.
Version : 1.5.9

**Comment by shortstuffsushi** [comment] 2015-07-16 13:03
Hey @SergeyMagid, if you're seeing issues on Android, you should log them against [the Android repository](BranchMetrics/Branch-Android-SDK). We can't fix them for you from within the iOS SDK ;)

**Comment by shortstuffsushi** [comment] 2015-08-17 15:11
Closing without any further feedback. Feel free to reopen if you're seeing problems.

**Comment by martinellimarco** [comment] 2015-09-03 12:04
Hi all,

I'm experiencing the same problem as @tomislav and reverting to 0.8.4 fixed it for me too.

I'm not using FB in my app, I'm only calling ```handleDeepLink``` in my openURL.

As described by @tomislav the callback is invoked only on resume and not on first launch but I can't see any timeout like he described.

There is another thing I've noticed, I'm using an url configured to pass query parameters. The url is like this one:
```
http://bnt.it/weeiam?c=12345
```

With the latest version of the sdk, on resume, I can see the parameter c correctly passed to my app. Then I change it, for example like this:
```
http://bnt.it/weeiam?c=98765
```

It still does not work on first launch but on resume I receive the parameter c but with value 12345, not 98765..

I don't know if those are two distinct bugs I'm hitting here or if it's all related but reverting to 0.8.4 fix all of this. (Parameter received on launch and on resume with updated value)

Any idea?

On Android it's working fine.

Other info:
iOS 8.4.1 (12H321) on iPhone 5s
Xcode 6.4

Best regards

**Comment by tomislav** [comment] 2015-09-03 13:01
I just tried it again with 0.10.9 and still having the issue. I even tried to fetch the parameters manually on launch with `[[Branch getInstance] getLatestReferringParams]` and all I get is an empty dictionary (not nil). Reverting to 0.8.4 makes it work again.

**Comment by martinellimarco** [comment] 2015-09-03 13:13
Hi tomislav,

if it's not a burden for you can you try with custom query parameters like in my example above (using ```$query_param_passthrough: true``` as described here https://dev.branch.io/link_configuration/ ) ?
I want to know if the problem we are facing is related or if I have to open a new issue.
If it's related maybe it can be an hint to help us.

Also, about the timeout messages you described, I can't see them using 0.10.9, can you still see them?

Thank you,
Regards

**Comment by tomislav** [comment] 2015-09-03 14:13
I did a little investigating and the last working version is 0.9.1 ... Looking through the commits after that I'm suspecting something was broken in `BNCPreferenceHelper` in 0.9.2 where it returns an empty `sessionParams`. 

Then I collected branch logs from opening links on app launch with versions 0.9.1 and 0.9.2.

0.9.1 = https://gist.github.com/tomislav/a0b7f77617de1e1839a9
0.9.2 = https://gist.github.com/tomislav/dccfee829db441d4b133

The payload data seems to get clobbered in 0.9.2 ?

**Comment by martinellimarco** [comment] 2015-09-03 14:45
I will test later with 0.9.1 and 0.9.2 and see how it works

**Comment by martinellimarco** [comment] 2015-09-03 15:58
I can confirm that on 0.9.1 the callback is invoked on launch and on resume but in 0.9.2 it's invoked only on resume.

**Comment by aaustin** [comment] 2015-09-03 16:00
Hey guys - I'll take a look at this today. Sorry about the issue!

**Comment by aaustin** [comment] 2015-09-03 18:58
Just so I can try to reproduce, the context:
1. Kill app from background
2. Run app form Xcode
3. Expected: deep link callback should be called
Reality: deep link callback not called

Or:
Expected: link parameters should be present in callback
Reality: link parameters not present in callback

**Comment by tomislav** [comment] 2015-09-03 19:04
1. Kill app
2. Open a branch link from Safari. In our case, for example http://htl.st/7xEc/Gh5Czvnqzm
3. Apps opens, callback not called. If you manually try to retrieve the link parameters you just get an empty dictionary.

Expected: on app launch the callback gets called with the link parameters

Setup is still as in the first post.

**Comment by martinellimarco** [comment] 2015-09-03 19:19
What I do in latest version:

1. Kill the app
2. Open a link from Safari, in my case it's ```http://bnt.it/weeiam?c=12345```
3. App opens, callback not invoked.
4. Leave app open in background, in Safari open again ```http://bnt.it/weeiam?c=12345```
5. App comes back in foreground, callback is invoked with parameter c=12345
6. Leave app open in background, in Safari change url to ```http://bnt.it/weeiam?c=98765```
7. App comes back in foreground, callback is invoked BUT parameter still c=12345 instead of c=98765

In working version:

1. Kill the app
2. Open a link from Safari, in my case it's ```http://bnt.it/weeiam?c=12345```
3. App opens, callback invoked, parameter c=12345
6. Leave app open in background (or kill, it's the same), in Safari change url to ```http://bnt.it/weeiam?c=98765```
7. App comes back in foreground, callback is invoked with parameter c=98765

**Comment by aaustin** [comment] 2015-09-04 01:10
Hmm - I just tested on 0.10.9 with Xcode and my iPhone6. If you kill the background process and start the process cold, Xcode won't connect and print the logs, so I had to go to Window -> Devices to monitor the logs. Here's what I saw:

```
Sep  3 18:06:41 Alexanders-iPhone SpringBoard[54] <Warning>: Application 'UIKitApplication:com.branch.sdk.Branch-TestBed[0xedf]' exited abnormally via signal.
Sep  3 18:07:01 Alexanders-iPhone Branch-TestBed[2157] <Error>: assertion failed: 12H321: libxpc.dylib + 71720 [6AAD6868-FD5B-3002-9EF4-5897E6B452AF]: 0x7d
Sep  3 18:07:01 Alexanders-iPhone Unknown[2157] <Error>: 
Sep  3 18:07:01 Alexanders-iPhone Branch-TestBed[2157] <Warning>: opened app from URL branchtest://open?link_click_id=128884764647098654
Sep  3 18:07:02 Alexanders-iPhone Branch-TestBed[2157] <Warning>: finished init with params = {
	    "$og_image_url" = "https://s3-us-west-1.amazonaws.com/branchhost/mosaic_og.png";
	    "$og_title" = Kindred;
	    "+click_timestamp" = 1441328818044;
	    "+clicked_branch_link" = 1;
	    "+is_first_session" = 0;
	    key1 = "test_object";
	    key2 = "here is another object!!";
	    "~channel" = facebook;
	    "~creation_source" = "iOS SDK";
	    "~feature" = invite;
	    "~stage" = 2;
	    "~tags" =     (
	        tag1,
	        tag2
	    );
	}
```

It looks like the parameters are being returned properly from cold start with my setup and testbed. Here's how my code is laid out in the AppDelegate. Can you guys confirm I'm doing the same thing as you?

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    Branch *branch = [Branch getInstance];
    [branch initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
        if (!error) {
            NSLog(@"finished init with params = %@", [params description]);
        } else {
            NSLog(@"failed init: %@", error);
        }
    }];
    return YES;
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    NSLog(@"opened app from URL %@", [url description]);
    return [[Branch getInstance] handleDeepLink:url];
}
```

**Comment by martinellimarco** [comment] 2015-09-04 06:04
Hi @aaustin , thank you for your work.

The code it's the same, I've just inserted the NSLog you're using.
Here there are the results using 0.10.9 on my iPhone 5s (iOS 8.4.1)

1: Kill the app
2: In safari I open ```http://bnc.lt/weeiam?c=12345```
3: App opens but the callback is not invoked
```
Sep  4 07:28:49 iPhone-di-Marco Weeiam[2354] <Error>: assertion failed: 12H321: libxpc.dylib + 51859 [70B3605C-8708-3424-BB0B-268F13BC8B3F]: 0x7d
Sep  4 07:28:49 iPhone-di-Marco Unknown[2354] <Error>: 
Sep  4 07:28:49 iPhone-di-Marco Weeiam[2354] <Warning>: Flurry: Starting session on Agent Version [Flurry_iOS_154_6.6.0] 
Sep  4 07:28:49 iPhone-di-Marco Weeiam[2354] <Warning>: opened app from URL weeiam://open?link_click_id=167721255003261086
Sep  4 07:28:49 iPhone-di-Marco Weeiam[2354] <Warning>: Warning: Libinfo call to mDNSResponder on main thread
```
4: App in background, in safari I open again the same url
5: App goes in foreground, this time the callback is invoked

```
Sep  4 07:36:53 iPhone-di-Marco Weeiam[2354] <Warning>: opened app from URL weeiam://open?link_click_id=167721255003261086
Sep  4 07:36:53 iPhone-di-Marco locationd[57] <Notice>: Gesture EnabledForTopCLient: 1, EnabledInDaemonSettings: 1
Sep  4 07:36:54 iPhone-di-Marco locationd[57] <Notice>: Gesture EnabledForTopCLient: 1, EnabledInDaemonSettings: 1
Sep  4 07:36:54 iPhone-di-Marco Weeiam[2354] <Warning>: finished init with params = {
    "$desktop_url" = "http://weeiam.com";
    "$marketing_title" = "Weeiam Share Link";
    "$og_image_url" = "https://cdn.branch.io/branch-assets/1441228436702-og_image.png";
    "$query_param_passthrough" = true;
    "+click_timestamp" = 1441345010945;
    "+clicked_branch_link" = 1;
    "+is_first_session" = 0;
    c = 12345;
    "~creation_source" = Dashboard; 
   "~feature" = marketing;
}
Sep  4 07:36:54 iPhone-di-Marco Weeiam[2354] <Warning>: query parameter c = 12345
```
6: App again in background, this time in Safari I try with another url: ```http://bnc.lt/weeiam?c=98765```
7: App goes in foreground, callback is invoked but as you can see c is still 12345
```
Sep  4 07:40:56 iPhone-di-Marco Weeiam[2359] <Error>: assertion failed: 12H321: libxpc.dylib + 51859 [70B3605C-8708-3424-BB0B-268F13BC8B3F]: 0x7d
Sep  4 07:40:56 iPhone-di-Marco Unknown[2359] <Error>: 
Sep  4 07:40:56 iPhone-di-Marco Weeiam[2359] <Warning>: Flurry: Starting session on Agent Version [Flurry_iOS_154_6.6.0] 
Sep  4 07:40:56 iPhone-di-Marco Weeiam[2359] <Warning>: opened app from URL weeiam://open?link_click_id=167721255003261086
Sep  4 07:40:56 iPhone-di-Marco Weeiam[2359] <Warning>: Warning: Libinfo call to mDNSResponder on main thread
Sep  4 07:40:57 iPhone-di-Marco Weeiam[2359] <Warning>: finished init with params = {
    "$desktop_url" = "http://weeiam.com";
    "$marketing_title" = "Weeiam Share Link";
    "$og_image_url" = "https://cdn.branch.io/branch-assets/1441228436702-og_image.png";
    "$query_param_passthrough" = true;
    "+click_timestamp" = 1441345251267;
    "+clicked_branch_link" = 1;
    "+is_first_session" = 0;
    c = 12345;
    "~creation_source" = Dashboard;
    "~feature" = marketing;
}
Sep  4 07:40:57 iPhone-di-Marco Weeiam[2359] <Warning>: query parameter c = 12345
```


This is with 0.8.4:

1: Kill the app
2: In safari I open ```http://bnc.lt/weeiam?c=12345```
3: App opens and the callback is correctly invoked
```
p  4 07:52:02 iPhone-di-Marco Weeiam[2377] <Error>: assertion failed: 12H321: libxpc.dylib + 51859 [70B3605C-8708-3424-BB0B-268F13BC8B3F]: 0x7d
Sep  4 07:52:02 iPhone-di-Marco Unknown[2377] <Error>: 
Sep  4 07:52:02 iPhone-di-Marco Weeiam[2377] <Warning>: Flurry: Starting session on Agent Version [Flurry_iOS_154_6.6.0] 
Sep  4 07:52:02 iPhone-di-Marco Weeiam[2377] <Warning>: opened app from URL weeiam://open?link_click_id=167721255003261086
Sep  4 07:52:02 iPhone-di-Marco Weeiam[2377] <Warning>: Warning: Libinfo call to mDNSResponder on main thread
Sep  4 07:52:03 iPhone-di-Marco Weeiam[2377] <Warning>: finished init with params = {
    "$desktop_url" = "http://weeiam.com";
    "$marketing_title" = "Weeiam Share Link";
    "$og_image_url" = "https://cdn.branch.io/branch-assets/1441228436702-og_image.png";
    "$query_param_passthrough" = true;
    "+click_timestamp" = 1441345921223;
    "+clicked_branch_link" = 1;
    "+is_first_session" = 0;
    c = 12345;
    "~creation_source" = Dashboard;
    "~feature" = marketing;
}
Sep  4 07:52:03 iPhone-di-Marco Weeiam[2377] <Warning>: query parameter c = 12345
```
4: In Safari I open ```http://bnc.lt/weeiam?c=98765```
5: App opens and the callback is correctly invoked, but this time, unexpectedly, the parameter c is still 12345.. I'm puzzled now since it always worked fine in previous tests with older version.. the code is untouched.. I will test more on this, maybe it's an unrelated issue? What do you think @aaustin ?
```
Sep  4 07:53:49 iPhone-di-Marco Weeiam[2378] <Error>: assertion failed: 12H321: libxpc.dylib + 51859 [70B3605C-8708-3424-BB0B-268F13BC8B3F]: 0x7d
Sep  4 07:53:49 iPhone-di-Marco Unknown[2378] <Error>: 
Sep  4 07:53:49 iPhone-di-Marco Weeiam[2378] <Warning>: Flurry: Starting session on Agent Version [Flurry_iOS_154_6.6.0] 
Sep  4 07:53:49 iPhone-di-Marco Weeiam[2378] <Warning>: opened app from URL weeiam://open?link_click_id=167721255003261086
Sep  4 07:53:49 iPhone-di-Marco Weeiam[2378] <Warning>: Warning: Libinfo call to mDNSResponder on main thread
Sep  4 07:53:50 iPhone-di-Marco Weeiam[2378] <Warning>: finished init with params = {
    "$desktop_url" = "http://weeiam.com";
    "$marketing_title" = "Weeiam Share Link";
    "$og_image_url" = "https://cdn.branch.io/branch-assets/1441228436702-og_image.png";
    "$query_param_passthrough" = true;
    "+click_timestamp" = 1441346023021;
    "+clicked_branch_link" = 1;
    "+is_first_session" = 0;
    c = 12345;
    "~creation_source" = Dashboard;
    "~feature" = marketing;
}
Sep  4 07:53:50 iPhone-di-Marco Weeiam[2378] <Warning>: query parameter c = 12345
```

Regards

**Comment by martinellimarco** [comment] 2015-09-04 08:48
I've just tested 0.10.9 in the simulator using an iPhone 6 with iOS 8.4.1 configuration and it worked just fine. The code is the exact same one I've used in the real device where it fails.

@aaustin you tested on a real iPhone 6 right? Unfortunately I don't have one to test, only a 5s

@tomislav what iPhone/iPad are you using? Have you tested using the simulator?

**Comment by martinellimarco** [comment] 2015-09-04 08:54
Tested with iPhone 5s on simulator, it works. I don't know what to think..

**Comment by tomislav** [comment] 2015-09-04 09:21
Doesn't work for me on the simulator or the device with 0.10.9. iPhone 5 and iPhone 6.

Here are my logs with the exact AppDelegate setup as written by @aaustin. This is so hard to debug because you can't attach the debugger immediately on cold start. Or I can't figure out a way to do it.

*Cold start:*
```
Sep  4 11:07:05 Tomislavs-iPhone Hitlist[221] <Warning>: encoded dictionary : {"ios_bundle_id":"com.hitlistapp.ios.adhoc","branch_key":"xxxxx","os_version":"9.0","device_fingerprint_id":"167962304342703406","os":"iOS","debug":1,"identity_id":"132924250574034782","ad_tracking_enabled":0,"uri_scheme":"hitlistapp","is_referrable":0,"sdk":"ios0.10.9","retryNumber":0,"app_version":"3.1","update":1}
Sep  4 11:07:05 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:153] using url = https://api.branch.io/v1/open
Sep  4 11:07:05 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:154] body = {
	    "ad_tracking_enabled" = 0;
	    "app_version" = "3.1";
	    "branch_key" = "xxxxxxx";
	    debug = 1;
	    "device_fingerprint_id" = 167962304342703406;
	    "identity_id" = 132924250574034782;
	    "ios_bundle_id" = "com.hitlistapp.ios.adhoc";
	    "is_referrable" = 0;
	    os = iOS;
	    "os_version" = "9.0";
	    retryNumber = 0;
	    sdk = "ios0.10.9";
	    update = 1;
	    "uri_scheme" = hitlistapp;
	}
Sep  4 11:07:05 Tomislavs-iPhone Hitlist[221] <Warning>: opened app from URL hitlistapp://open?link_click_id=137960778291513917
Sep  4 11:07:06 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:196] returned = Status: 200; Data: {
	    "browser_fingerprint_id" = "<null>";
	    data = "{\"$og_description\":\"Southeast Asia has an amazing history, incredible food and plenty of sun. Book immediately if not sooner. \",\"$og_image_url\":\"https://static.hitlistapp.com/media/CACHE/images/trips/35/14223920410_fc02de82ef_k/8cd47d5a4e37fac0f8bd52c2fb7bdd35.jpg\",\"$og_title\":\"Southeast Asia Adventure \",\"action\":\"trip\",\"id\":35,\"referring_user_id\":\"31459\",\"referring_user_name\":\"Tomislav Filipcic\",\"title\":\"Southeast Asia Adventure \",\"~channel\":\"other\",\"~feature\":\"trips\",\"~creation_source\":\"iOS SDK\",\"+click_timestamp\":1441357619743,\"+is_first_session\":false,\"+clicked_branch_link\":true}";
	    "device_fingerprint_id" = 167962304342703406;
	    identity = 31459;
	    "identity_id" = 132924250574034782;
	    link = "http://htl.st/j/Wd3Rt8pXYj";
	    "referring_identity" = 31459;
	    "session_id" = 168272959167797193;
	}
Sep  4 11:07:06 Tomislavs-iPhone Hitlist[221] <Warning>: encoded dictionary : {"identity_id":"132924250574034782","retryNumber":0,"identity":"31459","session_id":"168272959167797193","device_fingerprint_id":"167962304342703406","sdk":"ios0.10.9","branch_key":"xxxx"}
Sep  4 11:07:06 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:153] using url = https://api.branch.io/v1/profile
Sep  4 11:07:06 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:154] body = {
	    "branch_key" = "xxxx";
	    "device_fingerprint_id" = 167962304342703406;
	    identity = 31459;
	    "identity_id" = 132924250574034782;
	    retryNumber = 0;
	    sdk = "ios0.10.9";
	    "session_id" = 168272959167797193;
	}
Sep  4 11:07:06 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:196] returned = Status: 200; Data: {
	    "identity_id" = 132924250574034782;
	    link = "http://htl.st/j/Wd3Rt8pXYj";
	    "link_click_id" = 113360347036915450;
	    "referring_data" = "{\"referringUserId\":\"31363\",\"referringUsername\":\"Test\",\"source\":\"ios\"}";
	}
Sep  4 11:07:06 Tomislavs-iPhone Hitlist[221] <Warning>: encoded dictionary : {"identity_id":"132924250574034782","retryNumber":0,"identity":"31459","session_id":"168272959167797193","device_fingerprint_id":"167962304342703406","sdk":"ios0.10.9","branch_key":"xxxxx"}
Sep  4 11:07:06 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:153] using url = https://api.branch.io/v1/profile
Sep  4 11:07:06 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:154] body = {
	    "branch_key" = "xxxxx";
	    "device_fingerprint_id" = 167962304342703406;
	    identity = 31459;
	    "identity_id" = 132924250574034782;
	    retryNumber = 0;
	    sdk = "ios0.10.9";
	    "session_id" = 168272959167797193;
	}
Sep  4 11:07:07 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:196] returned = Status: 200; Data: {
	    "identity_id" = 132924250574034782;
	    link = "http://htl.st/j/Wd3Rt8pXYj";
	    "link_click_id" = 113360347036915450;
	    "referring_data" = "{\"referringUserId\":\"31363\",\"referringUsername\":\"Test\",\"source\":\"ios\"}";
	}
```

*Resume:*
```
Sep  4 11:08:41 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:196] returned = Status: 200; Data: {
	}
Sep  4 11:08:41 Tomislavs-iPhone Hitlist[221] <Warning>: opened app from URL hitlistapp://open?link_click_id=137960778291513917
Sep  4 11:08:41 Tomislavs-iPhone Hitlist[221] <Warning>: encoded dictionary : {"ios_bundle_id":"com.hitlistapp.ios.adhoc","branch_key":"xxxxx","os_version":"9.0","device_fingerprint_id":"167962304342703406","link_identifier":"137960778291513917","os":"iOS","debug":1,"identity_id":"132924250574034782","ad_tracking_enabled":0,"uri_scheme":"hitlistapp","is_referrable":0,"sdk":"ios0.10.9","retryNumber":0,"app_version":"3.1","update":1}
Sep  4 11:08:41 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:153] using url = https://api.branch.io/v1/open
Sep  4 11:08:41 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:154] body = {
	    "ad_tracking_enabled" = 0;
	    "app_version" = "3.1";
	    "branch_key" = "xxxxxx";
	    debug = 1;
	    "device_fingerprint_id" = 167962304342703406;
	    "identity_id" = 132924250574034782;
	    "ios_bundle_id" = "com.hitlistapp.ios.adhoc";
	    "is_referrable" = 0;
	    "link_identifier" = 137960778291513917;
	    os = iOS;
	    "os_version" = "9.0";
	    retryNumber = 0;
	    sdk = "ios0.10.9";
	    update = 1;
	    "uri_scheme" = hitlistapp;
	}
Sep  4 11:08:43 Tomislavs-iPhone Hitlist[221] <Warning>: [BNCServerInterface.m:196] returned = Status: 200; Data: {
	    "browser_fingerprint_id" = "<null>";
	    data = "{\"$og_description\":\"Southeast Asia has an amazing history, incredible food and plenty of sun. Book immediately if not sooner. \",\"$og_image_url\":\"https://static.hitlistapp.com/media/CACHE/images/trips/35/14223920410_fc02de82ef_k/8cd47d5a4e37fac0f8bd52c2fb7bdd35.jpg\",\"$og_title\":\"Southeast Asia Adventure \",\"action\":\"trip\",\"id\":35,\"referring_user_id\":\"31459\",\"referring_user_name\":\"Tomislav Filipcic\",\"title\":\"Southeast Asia Adventure \",\"~channel\":\"other\",\"~feature\":\"trips\",\"~creation_source\":\"iOS SDK\",\"+click_timestamp\":1441357715348,\"+is_first_session\":false,\"+clicked_branch_link\":true}";
	    "device_fingerprint_id" = 167962304342703406;
	    identity = 31459;
	    "identity_id" = 132924250574034782;
	    link = "http://htl.st/j/Wd3Rt8pXYj";
	    "referring_identity" = 31459;
	    "session_id" = 168273363762943140;
	}
Sep  4 11:08:43 Tomislavs-iPhone Hitlist[221] <Warning>: finished init with params = {
	    "$og_description" = "Southeast Asia has an amazing history, incredible food and plenty of sun. Book immediately if not sooner. ";
	    "$og_image_url" = "https://static.hitlistapp.com/media/CACHE/images/trips/35/14223920410_fc02de82ef_k/8cd47d5a4e37fac0f8bd52c2fb7bdd35.jpg";
	    "$og_title" = "Southeast Asia Adventure ";
	    "+click_timestamp" = 1441357715348;
	    "+clicked_branch_link" = 1;
	    "+is_first_session" = 0;
	    action = trip;
	    id = 35;
	    "referring_user_id" = 31459;
	    "referring_user_name" = "Tomislav Filipcic";
	    title = "Southeast Asia Adventure ";
	    "~channel" = other;
	    "~creation_source" = "iOS SDK";
	    "~feature" = trips;
	}
```

**Comment by aaustin** [comment] 2015-09-04 18:35
Ahh - interesting @tomislav. It looks like you're calling `setIdentity` immediately after `initSession` in the case of a cold start but not in the background case. Let me try that.

@martinellimarco I was using a real iPhone 6 but let me try with a simulator. Are you calling setIdentity as well after initSession? There could be some sort of race condition.

**Comment by tomislav** [comment] 2015-09-04 18:56
@aaustin you're right. I commented out setIdentify in my appdelegate and it's working properly.

**Comment by aaustin** [comment] 2015-09-04 18:57
can you add it in the callback to initSession instead?

**Comment by tomislav** [comment] 2015-09-04 19:02
I just did and it's working properly.

**Comment by martinellimarco** [comment] 2015-09-04 19:09
Yes, I forgot I was using setIdentity in another class of my app. Now the callback works on cold start, still I'm experiencing inconsistencing with query parameters. I've just tested 4 times, two times I've got the right parameter, the other two times I've got a parameter I was using for test hours ago.. I will open another issue, what do you think @aaustin  ?

**Comment by aaustin** [comment] 2015-09-04 21:38
Interesting - that sounds fishy for sure. How about email support@branch.io so we can share details of your app and config.

I'll close this one out for now.

**Closed** 2015-09-04 21:38 UTC
